// <auto-generated />
using System;
using System.Collections.Generic;
using HiddenIsle.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace dotnetHiddenIsle.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260805122452_MakeCoreSelfAndInventoryOwned")]
    partial class MakeCoreSelfAndInventoryOwned
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("Ability");
                });

            modelBuilder.Entity("AbilitySuits", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("AbilitySuits");
                });

            modelBuilder.Entity("Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Affection")
                        .HasColumnType("integer");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Card")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Distance")
                        .HasColumnType("integer");

                    b.Property<string>("Land")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("HiddenIsle.API.Models.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AbilityTrackXP")
                        .HasColumnType("integer");

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AgentLevel")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("Burdens")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("Class")
                        .HasColumnType("integer");

                    b.Property<string>("Culture")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Ideals")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Look")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Vices")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("Virtues")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("MagicalProficiency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<int>("ClockSegmentsFilled")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentRank")
                        .HasColumnType("integer");

                    b.Property<int>("MaxClockSegments")
                        .HasColumnType("integer");

                    b.Property<string>("SchoolName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("MagicalProficiency");
                });

            modelBuilder.Entity("MagicalSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("MagicalSource");
                });

            modelBuilder.Entity("SuitSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AbilitySuitsId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Harm")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("XP")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AbilitySuitsId");

                    b.ToTable("SuitSkill");
                });

            modelBuilder.Entity("Ability", b =>
                {
                    b.HasOne("HiddenIsle.API.Models.Agent", null)
                        .WithMany("Abilities")
                        .HasForeignKey("AgentId");
                });

            modelBuilder.Entity("AbilitySuits", b =>
                {
                    b.HasOne("HiddenIsle.API.Models.Agent", null)
                        .WithMany("AbilitySuits")
                        .HasForeignKey("AgentId");
                });

            modelBuilder.Entity("Contact", b =>
                {
                    b.HasOne("HiddenIsle.API.Models.Agent", null)
                        .WithMany("Contacts")
                        .HasForeignKey("AgentId");
                });

            modelBuilder.Entity("HiddenIsle.API.Models.Agent", b =>
                {
                    b.OwnsOne("CoreSelf", "CoreSelf", b1 =>
                        {
                            b1.Property<Guid>("AgentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AdultSelf")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("CoreSelfAdultSelf");

                            b1.Property<string>("ChildSelf")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("CoreSelfChildSelf");

                            b1.PrimitiveCollection<List<string>>("FulfilledVirtues")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("CoreSelfFulfilledVirtues");

                            b1.HasKey("AgentId");

                            b1.ToTable("Agents");

                            b1.WithOwner()
                                .HasForeignKey("AgentId");
                        });

                    b.OwnsOne("Inventory", "Inventory", b1 =>
                        {
                            b1.Property<Guid>("AgentId")
                                .HasColumnType("uuid");

                            b1.PrimitiveCollection<List<string>>("Items")
                                .IsRequired()
                                .HasColumnType("text[]")
                                .HasColumnName("InventoryItems");

                            b1.Property<int>("Load")
                                .HasColumnType("integer")
                                .HasColumnName("InventoryLoad");

                            b1.HasKey("AgentId");

                            b1.ToTable("Agents");

                            b1.WithOwner()
                                .HasForeignKey("AgentId");
                        });

                    b.Navigation("CoreSelf")
                        .IsRequired();

                    b.Navigation("Inventory")
                        .IsRequired();
                });

            modelBuilder.Entity("MagicalProficiency", b =>
                {
                    b.HasOne("HiddenIsle.API.Models.Agent", null)
                        .WithMany("MagicalProficiencies")
                        .HasForeignKey("AgentId");
                });

            modelBuilder.Entity("MagicalSource", b =>
                {
                    b.HasOne("HiddenIsle.API.Models.Agent", null)
                        .WithMany("MagicalSources")
                        .HasForeignKey("AgentId");
                });

            modelBuilder.Entity("SuitSkill", b =>
                {
                    b.HasOne("AbilitySuits", null)
                        .WithMany("Skills")
                        .HasForeignKey("AbilitySuitsId");
                });

            modelBuilder.Entity("AbilitySuits", b =>
                {
                    b.Navigation("Skills");
                });

            modelBuilder.Entity("HiddenIsle.API.Models.Agent", b =>
                {
                    b.Navigation("Abilities");

                    b.Navigation("AbilitySuits");

                    b.Navigation("Contacts");

                    b.Navigation("MagicalProficiencies");

                    b.Navigation("MagicalSources");
                });
#pragma warning restore 612, 618
        }
    }
}
